;Campaign is based on something in Rules.ini - house or side, probably house
;gs Fixed so that it goes by side, not country

; Allied progression
[GDI]
Anims=Anims
Sounds=GDISFX
1=MO20R_ALL01
2=MO20R_ALL02
3=MO20R_ALL03
4=MO20R_ALL04
5=MO20R_ALL05
6=MO20R_ALL06
7=MO20R_ALL07
8=MO20R_ALL08
9=MO20R_ALL09

; Soviet Progression
[Nod]
Anims=Anims
Sounds=NODSFX
1=MO20R_SOV01
2=MO20R_SOV02
3=MO20R_SOV03
4=MO20R_SOV04
5=MO20R_SOV05
6=MO20R_SOV06
7=MO20R_SOV07
8=MO20R_SOV08
9=MO20R_SOV09

; Epsilon Progression
[ThirdSide]
Anims=Anims
Sounds=NODSFX
1=MO20R_TRN01
2=MO20R_TRN02
3=MO20R_TRN03
4=MO20R_TRN04
5=MO20R_TRN05
6=MO20R_TRN06
7=MO20R_TRN07
8=MO20R_TRN08
9=MO20R_TRN09
10=MO20R_TRN10

[GDISFX]
Overlay=GSWEEP.AUD,60
TargetFlyIn=BESTBOX.AUD,75
EnterRegion=EFFICIEN.AUD,40
ExitRegion=
ClickRegion=

[NODSFX]
Overlay = NSWEEP.AUD, 60
TargetFlyIn = BESTBOX.AUD, 75
EnterRegion = EFFICIEN.AUD, 40
ExitRegion =
ClickRegion =

[Anims]
TextRect=92,322,332,78
Palette=MapSel.pal
1=SMLOGO.SHP,16,322,5
2=GLOBE.SHP,545,168,5
3=COMPASS.SHP,448,255,5

[MO20R_ALL01]
Scenario=MO20R_ALL01UMD.MAP
Description=768
VoiceOver=GDI-01.AUD
MapVQ=GDIMAP01.VQA
Overlays=RG02A.SHP,RN02A.SHP
Targets=1,180,80
ClickMap=GDICLK01.PCX
2=MO20R_ALL02

[MO20R_ALL02]
Scenario=MO20R_ALL02UMD.MAP
Description=769
VoiceOver=GDI-02.AUD
MapVQ=GDIMAP01.VQA
Overlays=RG03AB.SHP,RN03AB.SHP
Targets=1,290,88,218,108
ClickMap=GDICLK01.PCX
3=MO20R_ALL03

[MO20R_ALL03]
Scenario=MO20R_ALL03UMD.MAP
Description=769
VoiceOver=GDI-02.AUD
MapVQ=GDIMAP01.VQA
Overlays=RG03AB.SHP,RN03AB.SHP
Targets=1,290,88,218,108
ClickMap=GDICLK01.PCX
4=MO20R_ALL04

[MO20R_ALL04]
Scenario=MO20R_ALL04UMD.MAP
Description=770
VoiceOver=GDI-03A.AUD
MapVQ=GDIMAP01.VQA
Overlays=RG04A2.SHP,RN04A2.SHP
Targets=1,360,78
ClickMap=GDICLK01.PCX
5=MO20R_ALL05

[MO20R_ALL05]
Scenario=MO20R_ALL05UMD.MAP
Description=771
VoiceOver=GDI-03B.AUD
MapVQ=GDIMAP01.VQA
Overlays=RG03A.SHP,RN03A.SHP
Targets=1,290,88
ClickMap=GDICLK01.PCX
6=MO20R_ALL06

[MO20R_ALL06]
Scenario=MO20R_ALL06UMD.MAP
Description=772
VoiceOver=GDI-04.AUD
MapVQ=GDIMAP02.VQA
Overlays=RG05AB1.SHP,RN05AB1.SHP
Targets=1,188,183,280,256
ClickMap=GDICLK02.PCX
7=MO20R_ALL07

[MO20R_ALL07]
Scenario=MO20R_ALL07UMD.MAP
Description=772
VoiceOver=GDI-04.AUD
MapVQ=GDIMAP02.VQA
Overlays=RG05AB2.SHP,RN05AB2.SHP
Targets=1,188,183,280,256
ClickMap=GDICLK02.PCX
8=MO20R_ALL08

[MO20R_ALL08]
Scenario=MO20R_ALL08UMD.MAP
Description=772
VoiceOver=GDI-04.AUD
MapVQ=GDIMAP02.VQA
Overlays=RG05AB2.SHP,RN05AB2.SHP
Targets=1,188,183,280,256
ClickMap=GDICLK02.PCX
9=MO20R_ALL09

[MO20R_ALL09]
Scenario=MO20R_ALL09UMD.MAP
Description=772
VoiceOver=GDI-04.AUD
MapVQ=GDIMAP02.VQA
Overlays=RG05AB2.SHP,RN05AB2.SHP
Targets=1,188,183,280,256
ClickMap=GDICLK02.PCX

;****************************************************************************
; Soviet STAGES
;****************************************************************************

;[MO20R_SOV00]
;Scenario=MO20R_
;Description=
;VoiceOver=
;MapVQ=NODMAP01.VQA
;Overlays=TN01A.SHP,TG01A.SHP
;Targets=1,120,140
;ClickMap=NODCLK01.PCX
;1=Sov01

[MO20R_SOV01]
Scenario=MO20R_SOV01UMD.MAP
Description=787
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
2=MO20R_SOV02

[MO20R_SOV02]
Scenario=MO20R_SOV02UMD.MAP
Description=788
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
3=MO20R_SOV03

[MO20R_SOV03]
Scenario=MO20R_SOV03UMD.MAP
Description=789
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
4=MO20R_SOV04

[MO20R_SOV04]
Scenario=MO20R_SOV04UMD.MAP
Description=789
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
5=MO20R_SOV05

[MO20R_SOV05]
Scenario=MO20R_SOV05UMD.MAP
Description=790
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
6=MO20R_SOV06

[MO20R_SOV06]
Scenario=MO20R_SOV06UMD.MAP
Description=791
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
7=MO20R_SOV07

[MO20R_SOV07]
Scenario=MO20R_SOV07UMD.MAP
Description=791
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
8=MO20R_SOV08

[MO20R_SOV08]
Scenario=MO20R_SOV08UMD.MAP
Description=791
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
9=MO20R_SOV09

[MO20R_SOV09]
Scenario=MO20R_SOV09UMD.MAP
Description=791
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[MO20R_TRN01]
Scenario=MO20R_TRN01TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
2=MO20R_TRN02

[MO20R_TRN02]
Scenario=MO20R_TRN02TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
3=MO20R_TRN03

[MO20R_TRN03]
Scenario=MO20R_TRN03TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
4=MO20R_TRN04

[MO20R_TRN04]
Scenario=MO20R_TRN04TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
5=MO20R_TRN05

[MO20R_TRN05]
Scenario=MO20R_TRN05TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
6=MO20R_TRN06

[MO20R_TRN06]
Scenario=MO20R_TRN06TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
7=MO20R_TRN07

[MO20R_TRN07]
Scenario=MO20R_TRN07TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
8=MO20R_TRN08

[MO20R_TRN08]
Scenario=MO20R_TRN08TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
9=MO20R_TRN09

[MO20R_TRN09]
Scenario=MO20R_TRN09TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX
10=MO20R_TRN10

[MO20R_TRN10]
Scenario=MO20R_TRN10TMD.MAP
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

; Red Alert 2 

; RA2 Allieds

[RA2_all01t]
Scenario=RA2_all01t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all02s]
Scenario=RA2_all02s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all03u]
Scenario=RA2_all03u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all04u]
Scenario=RA2_all04u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all05s]
Scenario=RA2_all05s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all06u]
Scenario=RA2_all06u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all07t]
Scenario=RA2_all07t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all08u]
Scenario=RA2_all08u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all09t]
Scenario=RA2_all09t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all10s]
Scenario=RA2_all10s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all11t]
Scenario=RA2_all11t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_all12s]
Scenario=RA2_all12s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

; RA2 Soviets

[RA2_sov01t]
Scenario=RA2_sov01t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov1u]
Scenario=RA2_sov1u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov02t]
Scenario=RA2_sov02t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov03u]
Scenario=RA2_sov03u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov04s]
Scenario=RA2_sov04s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov05u]
Scenario=RA2_sov05u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov06t]
Scenario=RA2_sov06t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov07s]
Scenario=RA2_sov07s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov08u]
Scenario=RA2_sov08u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov09u]
Scenario=RA2_sov09u.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov10t]
Scenario=RA2_sov10t.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov11s]
Scenario=RA2_sov11s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[RA2_sov12s]
Scenario=RA2_sov12s.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

; Yuri Revenge

[YR_all01umd]
Scenario=YR_all01umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all02umd]
Scenario=YR_all02umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all03umd]
Scenario=YR_all03umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all04dmd]
Scenario=YR_all04dmd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all05umd]
Scenario=YR_all05umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all06umd]
Scenario=YR_all06umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_all07smd]
Scenario=YR_all07smd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov01umd]
Scenario=YR_sov01umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov02smd]
Scenario=YR_sov02smd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov03umd]
Scenario=YR_sov03umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov04dmd]
Scenario=YR_sov04dmd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov05umd]
Scenario=YR_sov05umd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov06lmd]
Scenario=YR_sov06lmd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX

[YR_sov07tmd]
Scenario=YR_sov07tmd.map
;Description=854
VoiceOver=NOD-01.AUD
MapVQ=NODMAP01.VQA
Overlays=TN02A.SHP,TG02A.SHP
Targets=1,190,100
ClickMap=NODCLK01.PCX