name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7

    # Compile it via .bat file
    - name: Compile Project
      shell: cmd
      run: BuildProject.bat

    # Compress with 7z
    - name: Zip Artifact
      run: 7z a -t7z -mx=9 -m0=lzma2 -ms=on -r -- MOR-${{ github.sha }}.7z ./build/*

    # Upload artifact to the GitHub
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        path: MOR-${{ github.sha }}.7z
        archive: false
