name: Update XNA CnCNet Client

on:
  workflow_dispatch:

env:
  REPO_NAME: MentalOmegaRedux
  UPDATE_BRANCH_NAME: update-client-binaries
  COMMIT_MESSAGE: Update client binaries to the latest version
  PR_TITLE: Update client binaries to the latest version
  PR_BODY: This is an automatic pull request to update client binaries triggered from CnCNet/xna-cncnet-client repository.

jobs:
  publish-update-pr:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Configure Git Repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git branch -d ${{ env.UPDATE_BRANCH_NAME }}
        git checkout -b ${{ env.UPDATE_BRANCH_NAME }}
    
    - name: Download latest XNA client release
      uses: robinraju/release-downloader@v1
      with:
        repository: CnCNet/xna-cncnet-client
        latest: true
        fileName: xna-cncnet-client*

    - name: Extract Release Contents
      run: |
        rm -r -fo "D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Source\CLIENT\Resources\Binaries"
        rm -r -fo "D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Source\CLIENT\Resources\BinariesNET8"
        7z x xna-cncnet-client-*.7z -y -oD:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Source\CLIENT
        rm xna-cncnet-client-*.7z

    - name: Check For Changes
      id: check_changes
      run: |
        if (git status --porcelain) {
          echo "changed=true" >> $env:GITHUB_ENV
        } else {
          echo "changed=false" >> $env:GITHUB_ENV
        }
    
    - name: Commit And Push Branch
      if: env.changed == 'true'
      run: |
        git commit -am "${{ env.COMMIT_MESSAGE }}"
        git push --force origin ${{ env.UPDATE_BRANCH_NAME }}

    - name: Open PR
      if: env.changed == 'true'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create -B main -H ${{ env.UPDATE_BRANCH_NAME }} --title '${{ env.PR_TITLE }}' --body '${{ env.PR_BODY }}'
