; = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  = 
; BATTLE.INI
;
; This control file specifies the battle campaigns that
; are in the game. Additional files that begin with "BATTLE"
; will augment this list.
;
; $Author: $
; $Archive: $
; $Modtime: $
; $Revision:$
; = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  = 

; ******* Battle List *******
; Lists the various battles in this control file. Each
; battle is given a unique (internal only) identifier name.
[Battles]

ALL01=ALL01
ALL02=ALL02
ALL03=ALL03
ALL04=ALL04
ALL05=ALL05
ALL06=ALL06
ALL07=ALL07
ALL08=ALL08
ALL09=ALL09 

SOV01=SOV01
SOV02=SOV02
SOV03=SOV03
SOV04=SOV04
SOV05=SOV05
SOV06=SOV06
SOV07=SOV07
SOV08=SOV08
SOV09=SOV09
 
TRN01=TRN01
TRN02=TRN02
TRN03=TRN03
TRN04=TRN04
TRN05=TRN05
TRN06=TRN06
TRN07=TRN07
TRN08=TRN08
TRN09=TRN09
TRN10=TRN10

;Red Alert 2

RA2_ALL01=RA2_ALL01
RA2_ALL02=RA2_ALL02
RA2_ALL03=RA2_ALL03
RA2_ALL04=RA2_ALL04
RA2_ALL05=RA2_ALL05
RA2_ALL06=RA2_ALL06
RA2_ALL07=RA2_ALL07
RA2_ALL08=RA2_ALL08
RA2_ALL09=RA2_ALL09
RA2_ALL10=RA2_ALL10
RA2_ALL11=RA2_ALL11
RA2_ALL12=RA2_ALL12 

RA2_SOV01=RA2_SOV01
RA2_SOV02=RA2_SOV02
RA2_SOV03=RA2_SOV03
RA2_SOV04=RA2_SOV04
RA2_SOV05=RA2_SOV05
RA2_SOV06=RA2_SOV06
RA2_SOV07=RA2_SOV07
RA2_SOV08=RA2_SOV08
RA2_SOV09=RA2_SOV09
RA2_SOV10=RA2_SOV10
RA2_SOV11=RA2_SOV11
RA2_SOV12=RA2_SOV12

;Yuri Revenge
YR_ALL01=YR_ALL01
YR_ALL02=YR_ALL02
YR_ALL03=YR_ALL03
YR_ALL04=YR_ALL04
YR_ALL05=YR_ALL05
YR_ALL06=YR_ALL06
YR_ALL07=YR_ALL07

YR_SOV01=YR_SOV01
YR_SOV02=YR_SOV02
YR_SOV03=YR_SOV03
YR_SOV04=YR_SOV04
YR_SOV05=YR_SOV05
YR_SOV06=YR_SOV06
YR_SOV07=YR_SOV07

; ******* Individual Campaign Data *******
; Each battle campaign lists its information
; in a section that cooresponds to its 
; identifier battle name (see above).

; CD = the CD that must be present to play the campaign [-1 means any CD]
; Scenario = MO20R_the scenario name for the first mission
; FinalMovie = finale movie to play at end of campaign (def = none)
; Description = string file label of text description of campaign for player choice list
; DebugOnly = this campaign is not for final release
;
;Everything below this line is place-holder and for debug purposes only.  REMOVE before shipping.  
;

[ALL01]
CD = -1
Scenario = MO20R_ALL01UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL02]
CD = -1
Scenario = MO20R_ALL02UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL03]
CD = -1
Scenario = MO20R_ALL03UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL04]
CD = -1
Scenario = MO20R_ALL04UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL05]
CD = -1
Scenario = MO20R_ALL05UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL06]
CD = -1
Scenario = MO20R_ALL06UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL07]
CD = -1
Scenario = MO20R_ALL07UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL08]
CD = -1
Scenario = MO20R_ALL08UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV

[ALL09]
CD = -1
Scenario = MO20R_ALL09UMD.MAP
FinalMovie = 
Description = NAME:ALL01MDSAV
  
[SOV01]
CD = -1
Scenario = MO20R_SOV01UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV02]
CD = -1
Scenario = MO20R_SOV02UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV03]
CD = -1
Scenario = MO20R_SOV03UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV04]
CD = -1
Scenario = MO20R_SOV04UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV05]
CD = -1
Scenario = MO20R_SOV05UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV06]
CD = -1
Scenario = MO20R_SOV06UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV07]
CD = -1
Scenario = MO20R_SOV07UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV08]
CD = -1
Scenario = MO20R_SOV08UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV

[SOV09]
CD = -1
Scenario = MO20R_SOV09UMD.MAP
FinalMovie = 
Description = NAME:SOV01MDSAV
 
[TRN01]
CD = -1
Scenario = MO20R_TRN01UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN02]
CD = -1
Scenario = MO20R_TRN02UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN03]
CD = -1
Scenario = MO20R_TRN03UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN04]
CD = -1
Scenario = MO20R_TRN04UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN05]
CD = -1
Scenario = MO20R_TRN05UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN06]
CD = -1
Scenario = MO20R_TRN06UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN07]
CD = -1
Scenario = MO20R_TRN07UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN08]
CD = -1
Scenario = MO20R_TRN08UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN09]
CD = -1
Scenario = MO20R_TRN09UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[TRN10]
CD = -1
Scenario = MO20R_TRN10UMD.MAP
FinalMovie = 
Description = NAME:TRN01MDSAV

[RA2_ALL01]
CD = -1
Scenario = RA2_ALL01T.map
FinalMovie = 
Description = 

[RA2_ALL02]
CD = -1
Scenario = RA2_ALL02S.map
FinalMovie = 
Description = 

[RA2_ALL03]
CD = -1
Scenario = RA2_ALL03U.map
FinalMovie = 
Description = 

[RA2_ALL04]
CD = -1
Scenario = RA2_ALL04U.map
FinalMovie = 
Description = 

[RA2_ALL05]
CD = -1
Scenario = RA2_ALL05S.map
FinalMovie = 
Description = 

[RA2_ALL06]
CD = -1
Scenario = RA2_ALL06U.map
FinalMovie = 
Description = 

[RA2_ALL07]
CD = -1
Scenario = RA2_ALL07T.map
FinalMovie = 
Description = 

[RA2_ALL08]
CD = -1
Scenario = RA2_ALL08U.map
FinalMovie = 
Description = 

[RA2_ALL09]
CD = -1
Scenario = RA2_ALL09T.map
FinalMovie = 
Description = 

[RA2_ALL10]
CD = -1
Scenario = RA2_ALL10S.map
FinalMovie = 
Description = 

[RA2_ALL11]
CD = -1
Scenario = RA2_ALL11T.map
FinalMovie = 
Description = 

[RA2_ALL12]
CD = -1
Scenario = RA2_ALL12S.map
FinalMovie = 
Description = 

[RA2_SOV01]
CD = -1
Scenario = RA2_SOV01T.map
FinalMovie = 
Description = 

[RA2_SOV02]
CD = -1
Scenario = RA2_SOV02T.map
FinalMovie = 
Description = 

[RA2_SOV03]
CD = -1
Scenario = RA2_SOV03U.map
FinalMovie = 
Description = 

[RA2_SOV04]
CD = -1
Scenario = RA2_SOV04S.map
FinalMovie = 
Description = 

[RA2_SOV05]
CD = -1
Scenario = RA2_SOV05U.map
FinalMovie = 
Description = 

[RA2_SOV06]
CD = -1
Scenario = RA2_SOV06T.map
FinalMovie = 
Description = 

[RA2_SOV07]
CD = -1
Scenario = RA2_SOV07S.map
FinalMovie = 
Description = 

[RA2_SOV08]
CD = -1
Scenario = RA2_SOV08U.map
FinalMovie = 
Description = 

[RA2_SOV09]
CD = -1
Scenario = RA2_SOV09U.map
FinalMovie = 
Description = 

[RA2_SOV10]
CD = -1
Scenario = RA2_SOV10T.map
FinalMovie = 
Description = 

[RA2_SOV11]
CD = -1
Scenario = RA2_SOV11S.map
FinalMovie = 
Description = 

[RA2_SOV12]
CD = -1
Scenario = RA2_SOV12S.map
FinalMovie = 
Description = 

[YR_ALL01]
CD = -1
Scenario = YR_ALL01UMD.map
FinalMovie = 
Description = 

[YR_ALL02]
CD = -1
Scenario = YR_ALL02UMD.map
FinalMovie = 
Description = 

[YR_ALL03]
CD = -1
Scenario = YR_ALL03UMD.map
FinalMovie = 
Description = 

[YR_ALL04]
CD = -1
Scenario = YR_ALL04DMD.map
FinalMovie = 
Description = 

[YR_ALL05]
CD = -1
Scenario = YR_ALL05UMD.map
FinalMovie = 
Description = 

[YR_ALL06]
CD = -1
Scenario = YR_ALL06UMD.map
FinalMovie = 
Description = 

[YR_ALL07]
CD = -1
Scenario = YR_ALL07SMD.map
FinalMovie = 
Description =  

[YR_SOV01]
CD = -1
Scenario = YR_SOV01UMD.map
FinalMovie = 
Description = 

[YR_SOV02]
CD = -1
Scenario = YR_SOV02SMD.map
FinalMovie = 
Description = 

[YR_SOV03]
CD = -1
Scenario = YR_SOV03UMD.map
FinalMovie = 
Description = 

[YR_SOV04]
CD = -1
Scenario = YR_SOV04DMD.MAP
FinalMovie = 
Description = 

[YR_SOV05]
CD = -1
Scenario = YR_SOV05UMD.MAP
FinalMovie = 
Description = 

[YR_SOV06]
CD = -1
Scenario = YR_SOV06LMD.MAP
FinalMovie = 
Description = 

[YR_SOV07]
CD = -1
Scenario = YR_SOV07TMD.MAP
FinalMovie = 
Description = 