[Phobos]
DigitalDisplay.Enable = true;MessageApplyHoverState = false            ; booleanMessageDisplayInCenter = false            ; booleanMessageDisplayInCenter.BoardOpacity = 40  ; integerMessageDisplayInCenter.LabelsCount = 6    ; integerMessageDisplayInCenter.RecordsCount = 12  ; integer
;SuperWeaponSidebar.RequiredSignificance = 1
[MultiPlayer]
Handle = PC
ChatColor = 7
LANChatColor = 0
Theme = Default
PingCustomTunnels = True
PlaySoundOnGameHosted = True
NotifyOnUserListChange = True
DisablePrivateMessagePopups = False
AllowPrivateMessagesFromState = 1
AutomaticCnCNetLogin = False
SkipConnectDialog = False
PersistentMode = False
AllowGameInvitesFromFriendsOnly = False

[Options]
Win8Compat = No
IsFirstRun = False
DoubleTapInterval = 30
ScrollDelay = 4
DragDistance = 8
Translation = en
WriteInstallationPathToRegistry = True
CheckforUpdates = True
GameSpeed = 2
Difficulty = 0
CampDifficulty = 0
ScrollMethod = 0
ScrollRate = 3
AutoScroll = yes
DetailLevel = 2
SidebarCameoText = yes
UnitActionLines = True
ShowHidden = True
ToolTips = True

[Channels]
YR = True
DTA = False
TI = False
MO = False
RR = False
RE = False
CNCR = False
TD = False
RA = False
D2K = False
TS = False
SS = False

[Video]
ForceLowestDetailLevel = False
Video.Windowed = False
NoWindowFrame = False
ClientResolutionX = 1600
ClientResolutionY = 900
BorderlessWindowedClient = False
VideoBackBuffer = False
UseDDWrapperForMapEditor = False
ScreenWidth = 1600
ScreenHeight = 900
StretchMovies = no

[Compatibility]
Renderer = CnC_DDraw

[Audio]
ClientVolume = 0.1
PlayMainMenuMusic = False
StopMusicOnMenu = False
SoundVolume = 0.2
VoiceVolume = 0.2
ScoreVolume = 0.2
IsScoreRepeat = no
IsScoreShuffle = True
SoundLatency = 9
InGameMusic = yes

[Intro]
Play = no

[Network]
Socket = 65535
NetCard = 0
NetID = ffcf,ffdf,ffcf,


