; MENTAL OMEGA THEMES (Version with themes)

[Themes]
1 = INTRO
2 = Grinder
3 = Power
4 = Fortification
5 = InDeep
6 = Tension
7 = EagleHunter
8 = IndustroFunk
9 = Jank
10 = 200Meters
11 = BlowItUp
12 = Destroy
13 = Burn
14 = SCORE
15 = LOADING
16 = CREDITS
17 = RA2Options
18 = Motorized
19 = 
20 = HM2

;RA2MD songs
21 = BrainFreeze
22 = Drok
23 = Deceiver
24 = PhatAttack
25 = BullyKit
26 = DefendTheBase
27 = Tactics
28 = TranceLVania

;newsongs
29 = 

MO20_000 = MentalOmegaTheme
MO20_001 = House
MO20_002 = ActOn
MO20_003 = MM
MO20_004 = Industrial
MO20_005 = MovingForces
MO20_006 = Accused
MO20_007 = MudRemix
MO20_008 = Probing
MO20_009 = Infiltration
MO20_010 = ReadyTheArmy
MO20_011 = Scarred
MO20_012 = MassProduction 
MO20_013 = Terminate
MO20_014 = TheGathering 
MO20_015 = AncientPresence 
MO20_016 = SurveyingTheLand
MO20_017 = 
MO20_018 = 

MPT_000 = AnicaCut
MPT_001 = AnicaDrugaStrana
MPT_002 = AnicaScorp
MPT_003 =  

FK_001 = BrainFreezeRemastered
FK_002 = VigilanteIntro
FK_003 = ActOnInstinctRenegateRemix
FK_004 = 
FK_005 = 
FK_006 = 
FK_007 = 
FK_008 = 
FK_009 = 
FK_010 = 
FK_011 = 
FK_012 = 
FK_013 = 
FK_014 = 
FK_015 = 
FK_016 = 
FK_017 = 
FK_018 = 
FK_019 = 

FK_020 = 
FK_021 = 
FK_022 = 
FK_023 = 
FK_024 = 
FK_025 = 
FK_026 = 
FK_027 = 
FK_028 = 
FK_029 = 

FK_030 = 
FK_031 = 
FK_032 = 
FK_033 = 
FK_034 = 
FK_035 = 
FK_036 = 
FK_037 = 
FK_038 = 
FK_039 = 

FK_040 = 
FK_041 = 
FK_042 = 
FK_043 = 
FK_044 = 
FK_045 = 
FK_046 = 
FK_047 = 
FK_048 = 
FK_049 = 

FK_050 = 
FK_051 = 
FK_052 = 
FK_053 = 
FK_054 = 
FK_055 = 
FK_056 = 
FK_057 = 
FK_058 = 
FK_059 = 

ArgCmdr_001 = ArgCmdr_ClosingHours
ArgCmdr_002 = ArgCmdr_FaceToFace
ArgCmdr_003 = ArgCmdr_MindControl
ArgCmdr_004 = ArgCmdr_Pharotek
ArgCmdr_005 = ArgCmdr_Processing
ArgCmdr_006 = ArgCmdr_TwinCannon
ArgCmdr_007 = 
ArgCmdr_008 = 
ArgCmdr_009 = 
ArgCmdr_010 = 


NDID_000 = ChildProtectiveServiceSong
NDID_001 = CivilizingPeople
NDID_002 = DeathParade
NDID_003 = EverythingMustGo
NDID_004 = 

Smiecu_000 = EndOfFreedom
Smiecu_001 = InfRevolve
Smiecu_002 = 

Nal_WT_001 = Nal_WT_TP_Adrenaline
Nal_WT_002 = Nal_WT_TP_Angular
Nal_WT_003 = Nal_WT_TP_Prism
Nal_WT_004 = Nal_WT_TP_Flash
Nal_WT_005 = Nal_WT_TP_Pyramid
Nal_WT_006 = Nal_WT_TP_2005
Nal_WT_007 = Nal_WT_TP_Constellation
Nal_WT_008 = Nal_WT_TP_Hastate
Nal_WT_009 = Nal_WT_TP_Triven
Nal_WT_010 = Nal_WT_TP_Akute
Nal_WT_011 = Nal_WT_Delta
Nal_WT_012 = Nal_WT_Undercover_Mission
Nal_WT_013 = 
Nal_WT_014 = 
Nal_WT_015 = 
Nal_WT_016 = 

; ******* Individual Theme Data *******
; The following sections supply the information specific to
; each theme declared.
;
; Name  =  display name of the theme (string label)
; Length  =  length of the theme (in minutes)
; Normal  =  Is it available through the in-game theme play list (def = yes)?
; Scenario  =  the scenario when the theme becomes available (def = 0)
; Side  =  which side [or sides] get to hear this theme
; Repeat  =  Does this theme always loop (def = no)?

;;;MENTAL OMEGA THEMES

[House]
Name=THEME:House
Sound=inthehouse
Normal=yes

[ActOn]
Name=THEME:ActOn
Sound=actoninvasion
Normal=yes

[MM]
Name=THEME:MM
Sound=mindmarch
Normal=yes

[Industrial]
Name=THEME:Industrial
Sound=industrial
Normal=yes

[MovingForces]
Name=THEME:MovingForces
Sound=movingforces
Normal=yes

[Accused]
Name=THEME:Accused
Sound=accused
Normal=yes

[MudRemix]
Name=THEME:MudRemix
Sound=mudremix
Normal=yes

[Probing]
Name=THEME:Probing
Sound=probing
Normal=yes

[Infiltration]
Name=THEME:Infiltration
Sound=infiltration
Normal=yes

[ReadyTheArmy]
Name=THEME:ReadyTheArmy
Sound=readythearmy
Normal=yes

[Scarred]
Name=THEME:Scarred
Sound=scarred
Normal=yes

[Terminate]
Name=THEME:Terminate
Sound=terminate
Normal=yes

[MassProduction]
Name=THEME:Mass
Sound=massproduction
Normal=yes

;;;CHINESE

[SurveyingTheLand]
;Name=THEME:SurveyingTheLand
Sound=surveyingtheland
Normal=no

[AncientPresence]
;Name=THEME:AncientPresence
Sound=ancientpresence
Normal=no

[TheGathering]
;Name=THEME:TheGathering
Sound=thegathering
Normal=no

[MentalOmegaTheme]
Name=THEME:MentalOmega
Sound=mentalomegatheme
Normal=no
Repeat=yes

;;;SPECIAL

[INTRO]
Name=THEME:Intro
Sound=mindmarch
Normal=no
Repeat=yes

[LOADING]
Sound=readythearmy
Normal=no
Repeat=yes

[CREDITS]
Sound=industrial
Normal=no
Repeat=yes

[SCORE]
Sound=probing
Normal=no
Repeat=yes

[RA2Options]
Sound=actoninvasion
Normal=no
Repeat=yes

;;;YR THEMES

[BrainFreeze]
Name=THEME:BrainFreeze
Sound=BrainFre
Normal=yes

[Drok]
Name=THEME:Drok
Sound=Drok
Normal=yes

[Deceiver]
Name=THEME:Deceiver
Sound=Deceiver
Normal=yes

[PhatAttack]
Name=THEME:PhatAttack
Sound=PhatAtta
Normal=yes

[BullyKit]
Name=THEME:BullyKit
Sound=Bully
Normal=yes

[DefendTheBase]
Name=THEME:DefendTheBase
Sound=Defend
Normal=yes

[Tactics]
Name=THEME:Tactics
Sound=Tactics
Normal=yes

[TranceLVania]
Name=THEME:TranceLVania
Sound=TranceLV
Normal=yes

;;RA2 THEMES

[200Meters]
Name=THEME:200Meters
Sound=200Meter
Normal=yes

[Power]
Name=THEME:Power
Sound=Power
Normal=yes

[Fortification]
Name=THEME:Fortification
Sound=Fortific
Normal=yes

[InDeep]
Name=THEME:InDeep
Sound=InDeep
Normal=yes

[Tension]
Name=THEME:Tension
Sound=Tension
Normal=yes

[EagleHunter]
Name=THEME:EagleHunter
Sound=EagleHun
Normal=yes

[IndustroFunk]
Name=THEME:IndustroFunk
Sound=Industro
Normal=yes

[Jank]
Name=THEME:Jank
Sound=Jank
Normal=yes

[Grinder]
Name=THEME:Grinder
Sound=Grinder
Normal=yes

[BlowItUp]
Name=THEME:BlowItUp
Sound=BlowItUp
Normal=yes

[Destroy]
Name=THEME:Destroy
Sound=Destroy
Normal=yes

[Burn]
Name=THEME:Burn
Sound=Burn
Normal=yes

[Motorized]
Name=THEME:Motorized
Sound=Motorize
Normal=yes

[HM2]
Name=THEME:HM2
Sound=HM2
Normal=yes

;Nero day in Disneyland

[ChildProtectiveServiceSong]
Name = THEME:ChildProtectiveSS
Sound = ChildProtectiveServiceSong
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; ;thirdside

[CivilizingPeople]
Name = THEME:CivilizingPeople
Sound = CivilizingPeople
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; 

[DeathParade]
Name = THEME:DeathParade
Sound = DeathParade
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[EverythingMustGo]
Name = THEME:EverythingMustGo
Sound = EverythingMustGo
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[AnicaCut]
Name = THEME:AnicaCut
Sound = AnicaCut
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[AnicaScorp]
Name = THEME:AnicaScorp
Sound = AnicaScorp
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[AnicaDrugaStrana]
Name = THEME:AnicaDrugaStrana
Sound = AnicaDrugaStrana
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[VigilanteIntro]
Name = THEME:VigilanteIntro
Sound = VigilanteIntro
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[EndOfFreedom]
Name = THEME:EndOfFreedom
Sound = EndOfFreedom
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[InfRevolve]
Name = THEME:InfRevolve
Sound = InfRevolve
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[BrainFreezeRemastered]
Name = THEME:BrainFreezeRemastered
Sound = BrainFreezeRemastered
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ActOnInstinctRenegateRemix]
Name = THEME:ActOnInstinctRenegateRemix
Sound = ActOnInstinctRenegateRemix
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_ClosingHours]
Name = THEME:ArgCmdr_ClosingHours
Sound = ArgCmdr_ClosingHours
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_FaceToFace]
Name = THEME:ArgCmdr_FaceToFace
Sound = ArgCmdr_FaceToFace
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_MindControl]
Name = THEME:ArgCmdr_MindControl
Sound = ArgCmdr_MindControl
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_Pharotek]
Name = THEME:ArgCmdr_Pharotek
Sound = ArgCmdr_Pharotek
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_Processing]
Name = THEME:ArgCmdr_Processing
Sound = ArgCmdr_Processing
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[ArgCmdr_TwinCannon]
Name = THEME:ArgCmdr_TwinCannon
Sound = ArgCmdr_TwinCannon
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

;Nalence Wings Tracks

[Nal_WT_Delta]
Name = THEME:Nal_WT_Delta
Sound = Nal_WT_Delta
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_Undercover_Mission]
Name = THEME:Nal_WT_Undercover_Mission
Sound = Nal_WT_Undercover_Mission
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Adrenaline]
Name = THEME:Nal_WT_TP_Adrenaline
Sound = Nal_WT_TP_Adrenaline
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Angular]
Name = THEME:Nal_WT_TP_Angular
Sound = Nal_WT_TP_Angular
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Prism]
Name = THEME:Nal_WT_TP_Prism
Sound = Nal_WT_TP_Prism
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Flash]
Name = THEME:Nal_WT_TP_Flash
Sound = Nal_WT_TP_Flash
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Pyramid]
Name = THEME:Nal_WT_TP_Pyramid
Sound = Nal_WT_TP_Pyramid
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_2005]
Name = THEME:Nal_WT_TP_2005
Sound = Nal_WT_TP_2005
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Constellation]
Name = THEME:Nal_WT_TP_Constellation
Sound = Nal_WT_TP_Constellation
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Hastate]
Name = THEME:Nal_WT_TP_Hastate
Sound = Nal_WT_TP_Hastate
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Triven]
Name = THEME:Nal_WT_TP_Triven
Sound = Nal_WT_TP_Triven
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod

[Nal_WT_TP_Akute]
Name = THEME:Nal_WT_TP_Akute
Sound = Nal_WT_TP_Akute
Normal = yes
Repeat = yes
;Side = gdi,nod,thirdside ; Nod 