
; AdvancedCommandBar Entries
;
; ButtonList
; This is a list of buttons that the user might desire on his command bar.
; This list orders buttons from left to right and right-justifies them.
; If the user inserts an 'x' into the list (i.e. "blah,x,thing, ...")
; it will leave an empty slot in the command bar between the appropriate
; entries.
;
; The supported entries are as follows:
;
; AttackMove
; AutoDeploy -- Currently unsupported.
; Beacon
; Cheer
; Deploy
; Guard
; PlanningMode
; Stop
; Team01
; Team02
; Team03
; TypeSelect


;
; This section is used for solo and skirmish games
;
[AdvancedCommandBar]
ButtonList = Team01,Team02,TypeSelect,Deploy,Guard,PlanningMode

;
; This section contains the configuration for multiplayer games
;
[MultiplayerAdvancedCommandBar]
ButtonList = Team01,Team02,TypeSelect,Deploy,Guard,PlanningMode,Beacon

[Sidebar]
HarvesterCounter.Show = yes
;HarvesterCounter.Label = <none> ; CSF entry key, default is pickaxe symbol
HarvesterCounter.ConditionYellow = 50%
HarvesterCounter.ConditionRed = 25%
;
SuperWeaponSidebar = false                    ; boolean
SuperWeaponSidebar.Pyramid = true             ; boolean
SuperWeaponSidebar.Interval = 0               ; integer, pixels
SuperWeaponSidebar.LeftOffset = 0             ; integer, pixels
SuperWeaponSidebar.CameoHeight = 48           ; integer, pixels
SuperWeaponSidebar.Max = 0                    ; integer
SuperWeaponSidebar.MaxColumns =               ; integer
